name: Update Resume PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-lang-all texlive-fonts-extra latexmk

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex

    - name: Clean Up
      run: latexmk -C

    - name: Compile LaTeX document
      run: latexmk -pdf -silent -cd main.tex

    - name: Display LaTeX Log
      if: failure()
      run: cat main.log

    - name: Checkout website repo
      uses: actions/checkout@v4
      with:  
        repository: ParikKukreja/Personal-Website
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: website
        persist-credentials: true

    - name: delete old resume pdf
      run: rm -f website/public/main.pdf

    - name: copy new resume to website
      run: cp main.pdf website/public/

    - name: commit and push to website repo
      working-directory: website
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ParikKukreja/Personal-Website.git
        git add public/main.pdf
        git commit -m "updated resume"
        git push origin main

    - name: Deploy to GitHub Pages
      working-directory: website
      run: |
        npm install
        npm run deploy
